#!/bin/bash
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/   
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___   
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/   
#                                    /_/           drxspace@gmail.com
#

# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS newline-delimited paths for selected files (only if local)
# It seems to me that the $() notation doesn't work here that's why I used the backticks
# Get only the first item from the SELECTED_FILES array
Fullname=`echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/ /\\ /g' | tr '\n' ':' | cut -f1 -d':'`

if [[ -f "${Fullname}" ]]; then
	mv "${Fullname}" "${Fullname}.ansi"
	iconv -f WINDOWS-1253 -t UTF8 -o "${Fullname}" "${Fullname}.ansi" || {
		rm "${Fullname}"; mv "${Fullname}.ansi" "${Fullname}";
		zenity --error --title="UTF-8 Convertion" --text="Couldn't convert ${Fullname} to UTF-8.";
	}
fi
