#!/bin/bash
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/   
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___   
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/   
#                                    /_/           drxspace@gmail.com
#

# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS newline-delimited paths for selected files (only if local)
# It seems to me that the $() notation doesn't work here that's why I used the backticks
# Get only the first item from the SELECTED_FILES array
Fullname="`echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/ /\\ /g' | tr '\n' ':' | cut -f1 -d':'`"

#if [[ -f "${Fullname}" ]] && [[ "${Fullname##*.}" == "srt" ]]; then
if [[ -f "${Fullname}" ]]; then
	[[ -z $(file -bi "${Fullname}" | grep "utf-8" 2>/dev/null) ]] && {
		mv "${Fullname}" "${Fullname}.ansi";
		iconv -f WINDOWS-1253 -t UTF8 -o "${Fullname}" "${Fullname}.ansi";
	} || {
		zenity --width=300 --error --title="UTF-8 Subtitles Convertor" --text="Couldn't convert subtitles ${Fullname} to UTF-8.\n\nSeems they have already been converted.";
	}
	[[ $(grep -o -c -E "’[[:blank:]]" "${Fullname}") -gt 0 ]] && sed -i "s/’[[:blank:]]/' /g" "${Fullname}"
	[[ $(grep -o -c -E "’[[:alpha:]]{2,}" "${Fullname}") -gt 0 ]] && sed -i "s/’/Ά/g" "${Fullname}"
fi
