#!/bin/bash
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/   
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___   
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/   
#                                    /_/           drxspace@gmail.com
#

GuiTextEditor=$(which gedit)
GuiTextEditor=${GuiTextEditor:-$(which gnome-text-editor)}

# It seems to me that the $() notation doesn't work here that's why I used the backticks
Fullname=`echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS[0]}" | sed 's/ /\\ /g' | tr -d '\n'`

if [[ -f "${Fullname}" ]]; then
	gksudo -u root -m "Open file ${Fullname##*/} for edit as root user." ${GuiTextEditor} "${Fullname}"
else
	notify-send "EditAsRoot" "${Fullname} isn't a regular file." -i face-surprise
fi
