#!/bin/bash
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/   
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___   
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/   
#                                    /_/           drxspace@gmail.com
#

CurrDir=${NAUTILUS_SCRIPT_CURRENT_URI#file://}
gksudo -u root -m "Open ${CurrDir//%20/ } in Nautilus with root user privileges." "nautilus --no-desktop $NAUTILUS_SCRIPT_CURRENT_URI"
