#!/bin/bash
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/   
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___   
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/   
#                                    /_/           drxspace@gmail.com
#

GuiTextEditor=$(which gedit)
Nautilus=$(which nautilus)

# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS newline-delimited paths for selected files (only if local)
# It seems to me that the $() notation doesn't work here that's why I used the backticks
# Get only the first item from the SELECTED_FILES array
Fullname="`echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/ /\\ /g' | tr '\n' ':' | cut -f1 -d':'`"

if [[ -f "${Fullname}" ]]; then
	gksudo -u root -m "Open file ${Fullname##*/} for edit as root user." "${GuiTextEditor:-$(which gnome-text-editor)}" "${Fullname}"
elif [[ -d "${Fullname}" ]]; then
	gksudo -u root -m "Open directory ${Fullname##*/} in Nautilus with root user privileges." "${Nautilus} --no-desktop" "${Fullname}"
else
	notify-send "OpenAsRoot" "${Fullname} isn't a regular file." -i face-surprise
fi
