#!/bin/bash
#
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/   
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___   
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/   
#                                    /_/           drxspace@gmail.com
#
# Open gnome-terminal in the directory that the selected file or directory exists

# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS newline-delimited paths for selected files (only if local)
# It seems to me that the $() notation doesn't work here that's why I used the backticks
# Get only the first item from the SELECTED_FILES array
CurrDir=`echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/ /\\ /g' | tr '\n' ':' | cut -f1 -d':'`

if [[ -f "${CurrDir}" ]]; then CurrDir=${NAUTILUS_SCRIPT_CURRENT_URI#file://}; fi # We need to substitute %20

[[ -f $(which gnome-terminal) ]] && $(which gnome-terminal) -t "${CurrDir//%20/ }" --working-directory="${CurrDir//%20/ }" || exit 1
