#!/bin/bash
#
# _________        ____  ____________         _______ ___________________
# ______  /__________  |/ /___  ____/________ ___    |__  ____/___  ____/
# _  __  / __  ___/__    / ______ \  ___  __ \__  /| |_  /     __  __/   
# / /_/ /  _  /    _    |   ____/ /  __  /_/ /_  ___ |/ /___   _  /___   
# \__,_/   /_/     /_/|_|  /_____/   _  .___/ /_/  |_|\____/   /_____/   
#                                    /_/           drxspace@gmail.com
#

# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS newline-delimited paths for selected files (only if local)
# It seems to me that the $() notation doesn't work here that's why I used the backticks
# Get only the first item from the SELECTED_FILES array
Fullname="`echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | sed 's/ /\\ /g' | tr '\n' ':' | cut -f1 -d':'`"

if [[ -f "${Fullname}" ]] && [[ "${Fullname##*.}" == "vtt" ]]; then
	if [[ -f "${Fullname%.*}.srt" ]]; then
		zenity  --width=300 \
			--question \
			--title="VTT2SRT Convertion" \
			--text="Couldn't convert ${Fullname} to SRT.\n\nFilename already exists. Replace it?"
		Replace=$?
	fi
	if [[ ${Replace:-0} -eq 0 ]]; then
		sed -e '1,3d' -e 's/\(:[0-9][0-9]\)\./\1,/g' -e '$ {/^$/d;}' "${Fullname}" | \
		awk 'BEGIN{row=1} NF {print $0} !NF {if(NR>1){printf "\n"}; printf "%d\n", row; row++}' > "${Fullname%.*}.srt"
	fi
fi
